server:
  port: 8000

spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/dev?useUnicode=true&characterEncoding=utf8
    username: zhang
    password: 123456

#log
logging:
  config: classpath:config/logback-spring.xml
  path: /application/log/system_logs